"""Change default user active status

Revision ID: 43a19d59c1c2
Revises: 649cc3957cec
Create Date: 2023-11-26 16:49:30.812233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43a19d59c1c2'
down_revision = '649cc3957cec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
